version: "3"

services:
    backend:
        build: ./backend
        volumes:
        - ./backend/:/backend # maps host diretory to internal container directory
        working_dir: /backend/
        command: sh entrypoint.sh
        env_file: .env
        ports:
            - "8000:8000"
        links:
        - db

    db:
        restart: always
        image: postgres:latest
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/
            - ./db:/docker-entrypoint-initdb.d

volumes:
    pgdata: